//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.OsipovaE2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ.
    /// </summary>
    // *** Start programmer edit section *** (Заказ CustomAttributes)

    // *** End programmer edit section *** (Заказ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказE", new string[] {
            "НомерЗаказа as \'Номер заказа\'",
            "ФИОЗаказчика as \'Ф и о заказчика\'",
            "АдресЗаказа as \'Адрес заказа\'",
            "СпособДоставки as \'Способ доставки\'",
            "Количество as \'Количество\'",
            "Номенклатура as \'Номенклатура\'",
            "Номенклатура.Материал as \'Материал\'"}, Hidden=new string[] {
            "Номенклатура.Материал"})]
    [MasterViewDefineAttribute("ЗаказE", "Номенклатура", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Материал")]
    [View("ЗаказL", new string[] {
            "НомерЗаказа as \'Номер заказа\'",
            "ФИОЗаказчика as \'Ф и о заказчика\'",
            "АдресЗаказа as \'Адрес заказа\'",
            "СпособДоставки as \'Способ доставки\'",
            "Количество as \'Количество\'",
            "Номенклатура.Материал as \'Материал\'"})]
    public class Заказ : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерЗаказа;
        
        private string fФИОЗаказчика;
        
        private string fАдресЗаказа;
        
        private string fСпособДоставки;
        
        private int fКоличество;
        
        private IIS.OsipovaE2.Номенклатура fНоменклатура;
        
        // *** Start programmer edit section *** (Заказ CustomMembers)

        // *** End programmer edit section *** (Заказ CustomMembers)

        
        /// <summary>
        /// АдресЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.АдресЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказ.АдресЗаказа CustomAttributes)
        [StrLen(255)]
        public virtual string АдресЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.АдресЗаказа Get start)

                // *** End programmer edit section *** (Заказ.АдресЗаказа Get start)
                string result = this.fАдресЗаказа;
                // *** Start programmer edit section *** (Заказ.АдресЗаказа Get end)

                // *** End programmer edit section *** (Заказ.АдресЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.АдресЗаказа Set start)

                // *** End programmer edit section *** (Заказ.АдресЗаказа Set start)
                this.fАдресЗаказа = value;
                // *** Start programmer edit section *** (Заказ.АдресЗаказа Set end)

                // *** End programmer edit section *** (Заказ.АдресЗаказа Set end)
            }
        }
        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Количество CustomAttributes)

        // *** End programmer edit section *** (Заказ.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Количество Get start)

                // *** End programmer edit section *** (Заказ.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (Заказ.Количество Get end)

                // *** End programmer edit section *** (Заказ.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Количество Set start)

                // *** End programmer edit section *** (Заказ.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (Заказ.Количество Set end)

                // *** End programmer edit section *** (Заказ.Количество Set end)
            }
        }
        
        /// <summary>
        /// НомерЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.НомерЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказ.НомерЗаказа CustomAttributes)
        public virtual int НомерЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.НомерЗаказа Get start)

                // *** End programmer edit section *** (Заказ.НомерЗаказа Get start)
                int result = this.fНомерЗаказа;
                // *** Start programmer edit section *** (Заказ.НомерЗаказа Get end)

                // *** End programmer edit section *** (Заказ.НомерЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.НомерЗаказа Set start)

                // *** End programmer edit section *** (Заказ.НомерЗаказа Set start)
                this.fНомерЗаказа = value;
                // *** Start programmer edit section *** (Заказ.НомерЗаказа Set end)

                // *** End programmer edit section *** (Заказ.НомерЗаказа Set end)
            }
        }
        
        /// <summary>
        /// СпособДоставки.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.СпособДоставки CustomAttributes)

        // *** End programmer edit section *** (Заказ.СпособДоставки CustomAttributes)
        [StrLen(255)]
        public virtual string СпособДоставки
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.СпособДоставки Get start)

                // *** End programmer edit section *** (Заказ.СпособДоставки Get start)
                string result = this.fСпособДоставки;
                // *** Start programmer edit section *** (Заказ.СпособДоставки Get end)

                // *** End programmer edit section *** (Заказ.СпособДоставки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.СпособДоставки Set start)

                // *** End programmer edit section *** (Заказ.СпособДоставки Set start)
                this.fСпособДоставки = value;
                // *** Start programmer edit section *** (Заказ.СпособДоставки Set end)

                // *** End programmer edit section *** (Заказ.СпособДоставки Set end)
            }
        }
        
        /// <summary>
        /// ФИОЗаказчика.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.ФИОЗаказчика CustomAttributes)

        // *** End programmer edit section *** (Заказ.ФИОЗаказчика CustomAttributes)
        [StrLen(255)]
        public virtual string ФИОЗаказчика
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.ФИОЗаказчика Get start)

                // *** End programmer edit section *** (Заказ.ФИОЗаказчика Get start)
                string result = this.fФИОЗаказчика;
                // *** Start programmer edit section *** (Заказ.ФИОЗаказчика Get end)

                // *** End programmer edit section *** (Заказ.ФИОЗаказчика Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.ФИОЗаказчика Set start)

                // *** End programmer edit section *** (Заказ.ФИОЗаказчика Set start)
                this.fФИОЗаказчика = value;
                // *** Start programmer edit section *** (Заказ.ФИОЗаказчика Set end)

                // *** End programmer edit section *** (Заказ.ФИОЗаказчика Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Номенклатура CustomAttributes)

        // *** End programmer edit section *** (Заказ.Номенклатура CustomAttributes)
        [PropertyStorage(new string[] {
                "Номенклатура"})]
        [NotNull()]
        public virtual IIS.OsipovaE2.Номенклатура Номенклатура
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Номенклатура Get start)

                // *** End programmer edit section *** (Заказ.Номенклатура Get start)
                IIS.OsipovaE2.Номенклатура result = this.fНоменклатура;
                // *** Start programmer edit section *** (Заказ.Номенклатура Get end)

                // *** End programmer edit section *** (Заказ.Номенклатура Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Номенклатура Set start)

                // *** End programmer edit section *** (Заказ.Номенклатура Set start)
                this.fНоменклатура = value;
                // *** Start programmer edit section *** (Заказ.Номенклатура Set end)

                // *** End programmer edit section *** (Заказ.Номенклатура Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказE", typeof(IIS.OsipovaE2.Заказ));
                }
            }
            
            /// <summary>
            /// "ЗаказL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказL", typeof(IIS.OsipovaE2.Заказ));
                }
            }
        }
    }
}
