//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.OsipovaE2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Материал.
    /// </summary>
    // *** Start programmer edit section *** (Материал CustomAttributes)

    // *** End programmer edit section *** (Материал CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("МатериалE", new string[] {
            "Номенклатура as \'Номенклатура\'",
            "Номенклатура.Материал as \'Материал\'",
            "Количество as \'Количество\'",
            "Склад as \'Склад\'",
            "Склад.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Номенклатура.Материал",
            "Склад.Наименование"})]
    [MasterViewDefineAttribute("МатериалE", "Номенклатура", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Материал")]
    [MasterViewDefineAttribute("МатериалE", "Склад", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class Материал : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private IIS.OsipovaE2.Склад fСклад;
        
        private IIS.OsipovaE2.Номенклатура fНоменклатура;
        
        private IIS.OsipovaE2.АктПриемки fАктПриемки;
        
        // *** Start programmer edit section *** (Материал CustomMembers)

        // *** End programmer edit section *** (Материал CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (Материал.Количество CustomAttributes)

        // *** End programmer edit section *** (Материал.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (Материал.Количество Get start)

                // *** End programmer edit section *** (Материал.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (Материал.Количество Get end)

                // *** End programmer edit section *** (Материал.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Материал.Количество Set start)

                // *** End programmer edit section *** (Материал.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (Материал.Количество Set end)

                // *** End programmer edit section *** (Материал.Количество Set end)
            }
        }
        
        /// <summary>
        /// Материал.
        /// </summary>
        // *** Start programmer edit section *** (Материал.Номенклатура CustomAttributes)

        // *** End programmer edit section *** (Материал.Номенклатура CustomAttributes)
        [PropertyStorage(new string[] {
                "Номенклатура"})]
        [NotNull()]
        public virtual IIS.OsipovaE2.Номенклатура Номенклатура
        {
            get
            {
                // *** Start programmer edit section *** (Материал.Номенклатура Get start)

                // *** End programmer edit section *** (Материал.Номенклатура Get start)
                IIS.OsipovaE2.Номенклатура result = this.fНоменклатура;
                // *** Start programmer edit section *** (Материал.Номенклатура Get end)

                // *** End programmer edit section *** (Материал.Номенклатура Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Материал.Номенклатура Set start)

                // *** End programmer edit section *** (Материал.Номенклатура Set start)
                this.fНоменклатура = value;
                // *** Start programmer edit section *** (Материал.Номенклатура Set end)

                // *** End programmer edit section *** (Материал.Номенклатура Set end)
            }
        }
        
        /// <summary>
        /// Материал.
        /// </summary>
        // *** Start programmer edit section *** (Материал.Склад CustomAttributes)

        // *** End programmer edit section *** (Материал.Склад CustomAttributes)
        [PropertyStorage(new string[] {
                "Склад"})]
        [NotNull()]
        public virtual IIS.OsipovaE2.Склад Склад
        {
            get
            {
                // *** Start programmer edit section *** (Материал.Склад Get start)

                // *** End programmer edit section *** (Материал.Склад Get start)
                IIS.OsipovaE2.Склад result = this.fСклад;
                // *** Start programmer edit section *** (Материал.Склад Get end)

                // *** End programmer edit section *** (Материал.Склад Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Материал.Склад Set start)

                // *** End programmer edit section *** (Материал.Склад Set start)
                this.fСклад = value;
                // *** Start programmer edit section *** (Материал.Склад Set end)

                // *** End programmer edit section *** (Материал.Склад Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.OsipovaE2.АктПриемки.
        /// </summary>
        // *** Start programmer edit section *** (Материал.АктПриемки CustomAttributes)

        // *** End programmer edit section *** (Материал.АктПриемки CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "АктПриемки"})]
        public virtual IIS.OsipovaE2.АктПриемки АктПриемки
        {
            get
            {
                // *** Start programmer edit section *** (Материал.АктПриемки Get start)

                // *** End programmer edit section *** (Материал.АктПриемки Get start)
                IIS.OsipovaE2.АктПриемки result = this.fАктПриемки;
                // *** Start programmer edit section *** (Материал.АктПриемки Get end)

                // *** End programmer edit section *** (Материал.АктПриемки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Материал.АктПриемки Set start)

                // *** End programmer edit section *** (Материал.АктПриемки Set start)
                this.fАктПриемки = value;
                // *** Start programmer edit section *** (Материал.АктПриемки Set end)

                // *** End programmer edit section *** (Материал.АктПриемки Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "МатериалE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МатериалE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МатериалE", typeof(IIS.OsipovaE2.Материал));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Материал.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfМатериал CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfМатериал CustomAttributes)
    public class DetailArrayOfМатериал : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.OsipovaE2.DetailArrayOfМатериал members)

        // *** End programmer edit section *** (IIS.OsipovaE2.DetailArrayOfМатериал members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Материал by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Материал.
        /// </summary>
        public DetailArrayOfМатериал(IIS.OsipovaE2.АктПриемки fАктПриемки) : 
                base(typeof(Материал), ((ICSSoft.STORMNET.DataObject)(fАктПриемки)))
        {
        }
        
        public IIS.OsipovaE2.Материал this[int index]
        {
            get
            {
                return ((IIS.OsipovaE2.Материал)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.OsipovaE2.Материал dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
