//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.OsipovaE2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Номенклатура.
    /// </summary>
    // *** Start programmer edit section *** (Номенклатура CustomAttributes)

    // *** End programmer edit section *** (Номенклатура CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НоменклатураE", new string[] {
            "КодМатериала as \'Код материала\'",
            "Материал as \'Материал\'",
            "Цена as \'Цена\'"})]
    [View("НоменклатураL", new string[] {
            "КодМатериала as \'Код материала\'",
            "Материал as \'Материал\'",
            "Цена as \'Цена\'"})]
    public class Номенклатура : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодМатериала;
        
        private string fМатериал;
        
        private double fЦена;
        
        // *** Start programmer edit section *** (Номенклатура CustomMembers)

        // *** End programmer edit section *** (Номенклатура CustomMembers)

        
        /// <summary>
        /// КодМатериала.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.КодМатериала CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.КодМатериала CustomAttributes)
        public virtual int КодМатериала
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.КодМатериала Get start)

                // *** End programmer edit section *** (Номенклатура.КодМатериала Get start)
                int result = this.fКодМатериала;
                // *** Start programmer edit section *** (Номенклатура.КодМатериала Get end)

                // *** End programmer edit section *** (Номенклатура.КодМатериала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.КодМатериала Set start)

                // *** End programmer edit section *** (Номенклатура.КодМатериала Set start)
                this.fКодМатериала = value;
                // *** Start programmer edit section *** (Номенклатура.КодМатериала Set end)

                // *** End programmer edit section *** (Номенклатура.КодМатериала Set end)
            }
        }
        
        /// <summary>
        /// Материал.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.Материал CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.Материал CustomAttributes)
        [StrLen(255)]
        public virtual string Материал
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.Материал Get start)

                // *** End programmer edit section *** (Номенклатура.Материал Get start)
                string result = this.fМатериал;
                // *** Start programmer edit section *** (Номенклатура.Материал Get end)

                // *** End programmer edit section *** (Номенклатура.Материал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.Материал Set start)

                // *** End programmer edit section *** (Номенклатура.Материал Set start)
                this.fМатериал = value;
                // *** Start programmer edit section *** (Номенклатура.Материал Set end)

                // *** End programmer edit section *** (Номенклатура.Материал Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.Цена CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.Цена CustomAttributes)
        public virtual double Цена
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.Цена Get start)

                // *** End programmer edit section *** (Номенклатура.Цена Get start)
                double result = this.fЦена;
                // *** Start programmer edit section *** (Номенклатура.Цена Get end)

                // *** End programmer edit section *** (Номенклатура.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.Цена Set start)

                // *** End programmer edit section *** (Номенклатура.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (Номенклатура.Цена Set end)

                // *** End programmer edit section *** (Номенклатура.Цена Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НоменклатураE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НоменклатураE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НоменклатураE", typeof(IIS.OsipovaE2.Номенклатура));
                }
            }
            
            /// <summary>
            /// "НоменклатураL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НоменклатураL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НоменклатураL", typeof(IIS.OsipovaE2.Номенклатура));
                }
            }
        }
    }
}
